version: '3.9'
services:
  go-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - 8080:8082
    networks:
      - go-net
networks:
  go-net:
    name: afronautas
    external: true